Launch in foreground.  Correct ordering of success declaration removal.

diff --git a/bin/mkvm b/bin/mkvm
--- a/bin/mkvm
+++ b/bin/mkvm
@@ -82,8 +82,8 @@ function mkvm() {
   generate_preseed
   generate_installer_image
   generate_vm_image
-  info "Launching VM im background."
-  launch_vm &
+  info "Launching VM."
+  launch_vm
 }
 
 
@@ -131,11 +131,11 @@ function create_directories() {
 
 
 function generate_preseed() {
-  rm -f "${success_file_preseed}" || fail "Failed to remove success declaration for preseed file."
   if test -e "${preseed_generated_file}"; then
     info "Generated preseed file is already present."
     return 0
   fi
+  rm -f "${success_file_preseed}" || fail "Failed to remove success declaration for preseed file."
   info "Generating preseed file."
   cp "${preseed_template_file}" "${preseed_generated_file}" || fail "Failed to copy preseed file."
   sed -i "s/password \$/password $(pass show "${pass_path}")/" "${preseed_generated_file}" || fail "Failed to inject password into preseed file."
@@ -148,11 +148,11 @@ function generate_preseed() {
 
 
 function generate_installer_image() {
-  rm -f "${success_file_installer_image}" || fail "Failed to remove success declaration for installer image."
   if test -e "${installer_image_generated}"; then
     info "Generated installer image is already present."
     return 0
   fi
+  rm -f "${success_file_installer_image}" || fail "Failed to remove success declaration for installer image."
   info "Generating installer image."
   unpack_image
   unpack_initrd
@@ -166,11 +166,11 @@ function generate_installer_image() {
 
 
 function generate_vm_image() {
-  rm -f "${success_file_vm_image}" || fail "Failed to remove success declaration for clean VM image."
   if test -e "${vm_image_clean}"; then
     info "Clean VM image is already present."
     return 0
   fi
+  rm -f "${success_file_vm_image}" || fail "Failed to remove success declaration for clean VM image."
   info "Generating clean VM image."
   initialize_vm_image
   install_os
