The networking is all kinds of broken, but this is what I thought it should look like.

diff --git a/bin/mkvm b/bin/mkvm
--- a/bin/mkvm
+++ b/bin/mkvm
@@ -17,13 +17,10 @@ function main() {
   mem_gb='4'
   mem_mb="$(( mem_gb * 1024 ))"
   vm_image_size='10G'
-  #control_center=~/control-center/stg
   control_center="${self_path}"/../..
   cpu_core_count=4
-  #subnet_with_mask="192.168.11.0/24"
-  subnet_with_mask="192.168.12.0/24"
-  #gateway="192.168.11.1"
-  gateway="192.168.12.1"
+  subnet_with_mask="192.168.11.0/24"
+  gateway="192.168.11.1"
 
   if ! test 1 = "${#}"; then
     fail "Wrong number of arguments.  Just specify a short hostname."
@@ -44,7 +41,6 @@ function main() {
   if ! grep -qE "^${dec_byte}\.${dec_byte}\.${dec_byte}\.${dec_byte}\$" <<< "${ip_address}"; then
     fail "Invalid IP address:  '${ip_address}'"
   fi
-  ip_address="$(sed 's/192\.168\.11\./192.168.12./' <<< "${ip_address}")"
 
   case "${arch}" in
     'i386')
@@ -96,15 +92,21 @@ function main() {
 
 
 function mkvm() {
-  INTERFACE_NUMBER="${port}" IP_ADDRESS="${ip_address}" sudo -E "${self_path}"/mkvmnet up || fail "Failed to bring up networking for:  '${hostname}'"
   create_directories
+  info "Locking."
   lock
+  info "Bringing up networking."
+  INTERFACE_NUMBER="${port}" IP_ADDRESS="${ip_address}" sudo -E "${self_path}"/mkvmnet up || fail "Failed to bring up networking for:  '${hostname}'"
+  info "Preparing to bring up VM."
   remove_stale_files
   generate_preseed
   generate_installer_image
   generate_vm_image
+  info "Bringing up VM."
   launch_vm
+  info "Bringing down networking."
   INTERFACE_NUMBER="${port}" IP_ADDRESS="${ip_address}" sudo -E "${self_path}"/mkvmnet down || fail "Failed to bring down networking for:  '${hostname}'"
+  info "Unlocking."
   unlock
 }
 
diff --git a/bin/mkvmnet b/bin/mkvmnet
--- a/bin/mkvmnet
+++ b/bin/mkvmnet
@@ -1,15 +1,33 @@
 #!/bin/bash
+#
 # Make VM network - configure networking on this machine for VMs.
+#
+# This script assumes that on this host NAT is only used for guest VMs.  Expect
+# problems if the host normally engages in NAT for other reasons.
+#
+# The host for test VMs probably should not have a corresponding test VM.  If
+# it is possible, it will probably require some extra network logic.
+#
+# Consider enabling routing with ansible, permanently.
+#   Edit/template:  /etc/sysctl.conf
+#   sysctl -p
+#
+# iptables rules are added and removed by rule specification.  It might be
+# better to remove rule numbers.  It might also be better to try to use -F to
+# flush all matches instead of -D to delete the first match.
 
 mode="${1}"
-# Test VM interface number is expected to be the SSH unique port number.
+host_external_interface="$(ip route | awk '/^default/ {print $5}')"
 host_external_ip_address="$(ip addr | awk -F '[ /]+' '/inet / {print $3}' | grep -v '^127\.0\.0\.1$' | head -n 1)"
-host_internal_ip_address='192.168.12.1'
+# Pull gateway address and subnet from ansible inventory.
+host_internal_ip_address='192.168.11.1'
 host_internal_subnet_bits='24'
+testvm_ssh_client='testvm-ssh-client'
 
 
 
 function main() {
+  # Test VM interface number is expected to be the SSH unique port number.
   interface_number="${INTERFACE_NUMBER}"
   if ! grep -qE '^[0-9]+$' <<< "${interface_number}"; then
     fail "Invalid interface number:  '${interface_number}'"
@@ -38,35 +56,35 @@ function main() {
 
 
 function down() {
-#  interfaces=( 
-#    $(
-#      ip addr | awk -F ': ' '/^[0-9]+: tap[0-9]+:/ {print $2}'
-#    ) 
-#  )
-#  iptables -t nat -F || fail "Failed to flush nat table."
-#  for interface in "${interfaces[@]}"; do
-
-#  done
+  ip route del "${ip_address}" dev "${interface}" src "${host_internal_ip_address}" table "${interface_number}" || fail "Failed to remove route for marked packets from test VM SSH client user."
+  ip rule del fwmark "${interface_number}" table "${interface_number}" || fail "Failed to set rule for marked packets from test VM SSH client user."
+  #iptables -t mangle -D OUTPUT -m owner --uid-owner "${testvm_ssh_client}" -d "${ip_address}" || fail "Failed to unmark packets from test VM SSH client user."
+  iptables -t mangle -D OUTPUT -m owner --uid-owner "${testvm_ssh_client}" -d "${ip_address}" -j MARK --set-mark "${interface_number}" || fail "Failed to unmark packets from SSH client user to test VM."
+  iptables -t nat -D POSTROUTING -s "${ip_address}" -o "${host_external_interface}" -j MARK --set-mark "${interface_number}" || fail "Failed to unmark packets from test VM."
+  iptables -t nat -D POSTROUTING -s "${ip_address}" -o "${host_external_interface}" -j SNAT --to-source "${host_external_ip_address}" || fail "Failed to deconfigure NAT."
   ip link delete "${interface}" || fail "Failed to delete TAP interface:  '${interface}'"
-#  cat > /proc/sys/net/ipv4/ip_forward <<< '0' || fail "Failed to disable IP forwarding:  '${interface}'"
+
+  ip route flush cache || fail "Failed to flush route cache."
 }
 
 
 function up() {
+  # Routing from host to internet gets broken when any test VM is up.
+
+  cat > /proc/sys/net/ipv4/ip_forward <<< '1' || fail "Failed to enable IP forwarding."
+
   ip tuntap add "${interface}" mode tap || fail "Failed to add TAP interface."
   ip address add "${host_internal_ip_address}/${host_internal_subnet_bits}" dev "${interface}" noprefixroute || fail "Failed to configure TAP interface."
   ip link set "${interface}" up || fail "Failed to bring up TAP interface."
-  ip route add "${ip_address}" dev "${interface}" src "${host_internal_ip_address}" || fail "Failed to set route."
 
-  # Maybe this should be done with sysctl as part of one-time setup.
-  # /etc/sysctl.conf
-  # sysctl -p
-  cat > /proc/sys/net/ipv4/ip_forward <<< '1' || fail "Failed to enable IP forwarding."
+  iptables -t nat -A POSTROUTING -s "${ip_address}" -o "${host_external_interface}" -j SNAT --to-source "${host_external_ip_address}" || fail "Failed to configure NAT."
+  iptables -t nat -A POSTROUTING -s "${ip_address}" -o "${host_external_interface}" -j MARK --set-mark "${interface_number}" || fail "Failed to mark packets from test VM." 
+  iptables -t mangle -A OUTPUT -m owner --uid-owner "${testvm_ssh_client}" -d "${ip_address}" -j MARK --set-mark "${interface_number}" || fail "Failed to mark packets from SSH client user to test VM."
 
-  # Flush.
-  #iptables -t nat -F || fail "Failed to flush nat table."
-  # Establish NAT.
-  #iptables -t nat -A POSTROUTING -o wlan0 -j SNAT --to-source "${host_external_ip_address}" || fail "Failed to configure SNAT target."
+  ip rule add fwmark "${interface_number}" table "${interface_number}" || fail "Failed to set rule for marked packets from test VM SSH client user."
+  ip route add "${ip_address}" dev "${interface}" src "${host_internal_ip_address}" table "${interface_number}" || fail "Failed to add route for marked packets from test VM SSH client user."
+
+  ip route flush cache || fail "Failed to flush route cache."
 }
 
 
