Try setting the MAC address and IP address.  Note some further goals.

diff --git a/bin/mkvm b/bin/mkvm
--- a/bin/mkvm
+++ b/bin/mkvm
@@ -26,6 +26,16 @@ function main() {
   if ! grep -qE '^[0-9]+$' <<< "${port}"; then
     fail "Invalid port number:  '${port}'"
   fi
+  mac_address="$(awk '/mac_address/ {print $2}' "${control_center}"/ansible/inventory/inventory.d/host_vars/"${host}".yml | sed "s/['\"]//g")"
+  hex_byte='[a-fA-F0-9]{2}'
+  if ! grep -qE "^${hex_byte}:${hex_byte}:${hex_byte}:${hex_byte}:${hex_byte}:${hex_byte}\$" <<< "${mac_address}"; then
+    fail "Invalid MAC address:  '${mac_address}'"
+  fi
+  ip_address="$(awk '/ip_address/ {print $2}' "${control_center}"/ansible/inventory/inventory.d/host_vars/"${host}".yml | sed "s/['\"]//g")"
+  dec_byte='([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])'
+  if ! grep -qE "^${dec_byte}\.${dec_byte}\.${dec_byte}\.${dec_byte}\$" <<< "${ip_address}"
+    fail "Invalid IP address:  '${ip_address}'"
+  fi
 
   case "${arch}" in
     'i386')
@@ -174,6 +184,7 @@ function generate_preseed() {
   ssh_host_key_public="$(cat "${ssh_host_key_public_file}")" || fail "Failed to read SSH public key."
   sed -i "s#ssh_host_key_public#${ssh_host_key_public}#" "${preseed_generated_file}" || fail "Failed to inject SSH public key into preseed file."
   touch "${success_file_preseed}" || fail "Failed to declare success after generating preseed file."
+  sed -i "s/ip_address\$/${ip_address}/" "${preseed_generated_file}" || fail "Failed to inject IP address into preseed file."
 }
 
 
@@ -222,7 +233,7 @@ boot_this_image() {
   image_file="${1}"
   shift 1
   qemu-system-x86_64 \
-    -nic user,hostfwd=tcp::"${port}"-:22 \
+    -nic user,hostfwd=tcp::"${port}"-:22,mac="${mac_address}" \
     -machine pc \
     -cpu max \
     -smp cores="${cpu_core_count}" \
