Update OS to Trixie.  Start pursuing a new network strategy.  This succeed in bringing up a host named gateway with no intervention, but much more work is still needed.

diff --git a/bin/mkvm b/bin/mkvm
--- a/bin/mkvm
+++ b/bin/mkvm
@@ -12,8 +12,8 @@ function main() {
   #arch='armhf'
   arch='amd64'
   os='debian'
-  release='bookworm'
-  version='12.11.0'
+  release='trixie'
+  version='13.3.0'
   mem_gb='4'
   mem_mb="$(( mem_gb * 1024 ))"
   vm_image_size='10G'
@@ -21,16 +21,17 @@ function main() {
   cpu_core_count=4
   subnet_with_mask="192.168.11.0/24"
   gateway="192.168.11.1"
+  cpu_model='Broadwell-v4'
+  mcast='230.0.0.1:1234'
+  ifname='eth0'
+  local_net_id='vmnet'
+  upstream_net_id='upnet'
 
   if ! test 1 = "${#}"; then
     fail "Wrong number of arguments.  Just specify a short hostname."
   fi
   hostname="${1}"
 
-  port="$(awk '/^ssh_unique_port/ {print $2}' "${control_center}"/ansible/inventory/inventory.d/host_vars/"${hostname}".yml | head -n 1 | sed "s/['\"]//g")"
-  if ! grep -qE '^[0-9]+$' <<< "${port}"; then
-    fail "Invalid port number:  '${port}'"
-  fi
   mac_address="$(awk '/^mac_address/ {print $2}' "${control_center}"/ansible/inventory/inventory.d/host_vars/"${hostname}".yml | head -n 1 | sed "s/['\"]//g")"
   hex_byte='[a-fA-F0-9]{2}'
   if ! grep -qE "^${hex_byte}:${hex_byte}:${hex_byte}:${hex_byte}:${hex_byte}:${hex_byte}\$" <<< "${mac_address}"; then
@@ -95,16 +96,11 @@ function mkvm() {
   create_directories
   info "Locking."
   lock
-  info "Bringing up networking."
-  INTERFACE_NUMBER="${port}" IP_ADDRESS="${ip_address}" sudo -E "${self_path}"/mkvmnet up || fail "Failed to bring up networking for:  '${hostname}'"
-  info "Preparing to bring up VM."
   remove_stale_files
   generate_preseed
   generate_installer_image
   generate_vm_image
   launch_vm
-  info "Bringing down networking."
-  INTERFACE_NUMBER="${port}" IP_ADDRESS="${ip_address}" sudo -E "${self_path}"/mkvmnet down || fail "Failed to bring down networking for:  '${hostname}'"
   info "Unlocking."
   unlock
 }
@@ -195,6 +191,9 @@ function generate_preseed() {
   sed -i "s#ssh_host_key_public#${ssh_host_key_public}#" "${preseed_generated_file}" || fail "Failed to inject SSH public key into preseed file."
   touch "${success_file_preseed}" || fail "Failed to declare success after generating preseed file."
   sed -i "s/ip_address\$/${ip_address}/" "${preseed_generated_file}" || fail "Failed to inject IP address into preseed file."
+  if ! test 'gateway' = "${hostname}"; then
+    sed -i 's/^#d-i netcfg/d-i netcfg/'  "${preseed_generated_file}" || fail "Failed to disable IP autoconfiguration."
+  fi
 }
 
 
@@ -241,18 +240,40 @@ function launch_vm() {
 
 # boot_this_image <vm_image_file>
 boot_this_image() {
+  # What happens if there is no mcast specification?
+  # Can interface name (visible to OS) be specified for virtio-net-pci?
   image_file="${1}"
+
+  # The first network interface will be labeled ens3, and the second will be
+  # ens4.  The preseed template specifies ens3 as the interface to configure.
+  net_args=()
+  if test 'gateway' = "${hostname}"; then
+  net_args+=(
+    -netdev user,id="${upstream_net_id}"
+    -device virtio-net-pci,netdev="${upstream_net_id}"
+  )
+  fi
+  net_args+=(
+    -device virtio-net-pci,netdev="${local_net_id}",mac="${mac_address}"
+    -netdev socket,id="${local_net_id}",mcast="${mcast}"
+  )
+
   shift 1
   qemu-system-x86_64 \
-    -nic tap,id="${hostname}",mac="${mac_address}",ifname="tap${port}",script=no,downscript=no \
-    -machine pc \
-    -cpu max \
+    -name "${vm}" \
+    -machine accel=kvm \
+    -cpu "${cpu_model}" \
     -smp cores="${cpu_core_count}" \
     -m "${mem_mb}" \
-    -hda "${image_file}" \
+    "${net_args[@]}" \
+    -vga virtio \
+    "${image_file}" \
     "${@}" \
     > /dev/null \
-    < /dev/null
+    < /dev/null \
+  ;
+  # -hda "${image_file}"
+  # -vga none
 }
 
 
@@ -267,13 +288,14 @@ function wait_for_ssh() {
 
 
 function sshvm() {
-  sshpass \
-    -d 3 \
-    ssh \
-      -p "${port}" \
-      root@127.0.0.1 \
-      "${@}" \
-    3< <(pass show "${pass_path}")
+#  sshpass \
+#    -d 3 \
+#    ssh \
+#      -p "${port}" \
+#      root@127.0.0.1 \
+#      "${@}" \
+#    3< <(pass show "${pass_path}")
+  false
 }
 
 
@@ -282,7 +304,7 @@ function unpack_image() {
     chmod -R u+rwX "${unpack}" || fail "Failed to prepare installer unpack directory for deletion:  '${unpack}'"
     rm -rf "${unpack}" || fail "Failed to remove installer unpack directory:  '${unpack}'"
   fi
-  7zz x -o"${unpack}/" "${installer_image_original}" || fail "Failed to unpack installer image:  '${installer_image_generated}'"
+  7z x -o"${unpack}/" "${installer_image_original}" || fail "Failed to unpack installer image:  '${installer_image_generated}'"
 }
 
 
