Encrypt root.

diff --git a/lib/mkbs_functions/mount b/lib/mkbs_functions/mount
--- a/lib/mkbs_functions/mount
+++ b/lib/mkbs_functions/mount
@@ -6,13 +6,21 @@ function unmount_prep() {
     sudo umount -R "${target_mount_point}" \
       || fail "Failed to preparatively unmount mount points."
   fi
+  if test -e /dev/mapper/"${host}"-root; then
+    sudo vgchange -a n "${host}" \
+      || fail "Failed to preparatively deactivate volume group over LUKS."
+  fi
+  if test -e /dev/mapper/"${host}"_crypt; then
+    sudo cryptsetup close "${host}"_crypt \
+      || fail "Failed to preparatively close LUKS volume."
+  fi
 }
 
 
 function mount_partitions() {
   sudo mkdir -p "${target_mount_point}" \
     || fail "Failed to create target mount point."
-  sudo mount "${device}"3 "${target_mount_point}" \
+  sudo mount /dev/mapper/"${host}"-root "${target_mount_point}" \
     || fail "Failed to mount root/boot partition."
   sudo mkdir -p "${target_mount_point}"/boot \
     || fail "Failed to create boot mount point."
@@ -34,12 +42,19 @@ function mount_virtual_filesystems() {
     || fail "Failed to mount dev."
   sudo mount -t devpts devpts "${target_mount_point}"/dev/pts \
     || fail "Failed to mount dev/pts."
-  sudo tee "${target_mount_point}"/etc/hostname <<< bootstick \
-    || fail "Failed to write hostname."
+  sudo mkdir -p "${target_mount_point}"/run/udev \
+    || fail "Failed to create mount point for bind-mount:  /run/udev."
+  sudo mount --bind /run/udev "${target_mount_point}"/run/udev \
+    || fail "Failed to bind-mount:  /run/udev"
 }
 
 
 function unmount_all() {
   sudo umount -R "${target_mount_point}" \
-    || fail "Failed to unmount bootstick."
+    || fail "Failed to unmount ${host}."
+  sudo vgchange -a n "${host}" \
+    || fail "Failed to deactivate volume group over LUKS."
+  sudo cryptsetup close "${host}"_crypt \
+    || fail "Failed to close LUKS volume."
+
 }
diff --git a/lib/mkbs_functions/partition b/lib/mkbs_functions/partition
--- a/lib/mkbs_functions/partition
+++ b/lib/mkbs_functions/partition
@@ -30,7 +30,7 @@ function partition() {
     sleep .1
   done
   echo
-  sudo mkfs.ext4 -F -L bootstick_boot "${device}"2 \
+  sudo mkfs.ext4 -F -L "${host}"_boot "${device}"2 \
     || fail "Failed to write FS to boot partition."
   sudo tune2fs -i 0 -c 0 "${device}"2 \
     || fail "Failed to tune FS parameters for boot partition."
@@ -44,8 +44,27 @@ function partition() {
     sleep .1
   done
   echo
-  sudo mkfs.ext4 -F -L bootstick_root "${device}"3 \
+  # Are you sure you want to blow away this partition?  YES
+  {
+    pass show aaron/"${host}"/luks \
+      || fail "Failed to retrieve password for LUKS."
+  } \
+  | sudo cryptsetup luksFormat --key-file - "${device}"3 \
+    || fail "Failed to format for LUKS."
+  {
+    pass show aaron/"${host}"/luks \
+      || fail "Failed to retrieve password for LUKS."
+  } \
+  | sudo cryptsetup open --key-file - --type luks "${device}"3 "${host}"_crypt \
+    || fail "Failed to open LUKS volume."
+  sudo pvcreate /dev/mapper/"${host}"_crypt \
+    || fail "Failed to create LVM physical volume over LUKS."
+  sudo vgcreate "${host}" /dev/mapper/"${host}"_crypt \
+    || fail "Failed to create volume group over LUKS."
+  sudo lvcreate -l 100%FREE -n root "${host}" \
+    || fail "Failed to create logical volume for root."
+  sudo mkfs.ext4 -F -L "${host}"_root /dev/mapper/"${host}"-root \
     || fail "Failed to write FS to root partition."
-  sudo tune2fs -i 0 -c 0 "${device}"3 \
+  sudo tune2fs -i 0 -c 0 /dev/mapper/"${host}"-root \
     || fail "Failed to tune FS parameters for root partition."
 }
