Install GRUB for both BIOS (legacy) and EFI.  Reduce partition sizes.

diff --git a/lib/mkbs_functions/partition b/lib/mkbs_functions/partition
--- a/lib/mkbs_functions/partition
+++ b/lib/mkbs_functions/partition
@@ -4,24 +4,16 @@
 function partition() {
   sudo parted -s "${device}" mklabel gpt \
     || fail "Failed to write partition table."
-  sudo parted -s "${device}" mkpart primary fat32 1MiB 513MiB \
+  sudo parted -s "${device}" mkpart primary fat32 1MiB 2MiB \
+    || fail "Failed to create BIOS boot partition."
+  sudo parted -s "${device}" set 1 bios_grub on \
+    || fail "Failed to set bios_grub flag."
+  sudo parted -s "${device}" mkpart primary fat32 2MiB 256MiB \
     || fail "Failed to create ESP."
-  sudo parted -s "${device}" set 1 esp on \
+  sudo parted -s "${device}" set 2 esp on \
     || fail "Failed to set esp flag."
   # Apparently parted will return after writing a partition, but before the new
   # partition is visible as a device file.
-  for i in {0..99}; do
-    if test -a "${device}"1; then
-      break
-    fi
-    echo -n .
-    sleep .1
-  done
-  echo
-  sudo mkfs.vfat "${device}1" \
-    || fail "Failed to write FS to ESP."
-  sudo parted -s "${device}" mkpart primary ext4 513MiB 2GiB \
-    || fail "Failed to create boot partition."
   for i in {0..99}; do
     if test -a "${device}"2; then
       break
@@ -30,12 +22,10 @@ function partition() {
     sleep .1
   done
   echo
-  sudo mkfs.ext4 -F -L "${host}"_boot "${device}"2 \
-    || fail "Failed to write FS to boot partition."
-  sudo tune2fs -i 0 -c 0 "${device}"2 \
-    || fail "Failed to tune FS parameters for boot partition."
-  sudo parted -s "${device}" mkpart primary ext4 2GiB 100% \
-    || fail "Failed to create root partition."
+  sudo mkfs.vfat "${device}2" \
+    || fail "Failed to write FS to ESP."
+  sudo parted -s "${device}" mkpart primary ext4 256MiB 512MiB \
+    || fail "Failed to create boot partition."
   for i in {0..99}; do
     if test -a "${device}"3; then
       break
@@ -44,18 +34,36 @@ function partition() {
     sleep .1
   done
   echo
+  sudo mkfs.ext4 -F -L "${host}"_boot "${device}"3 \
+    || fail "Failed to write FS to boot partition."
+  sudo tune2fs -i 0 -c 0 "${device}"3 \
+    || fail "Failed to tune FS parameters for boot partition."
+  sudo parted -s "${device}" mkpart primary ext4 512MiB 100% \
+    || fail "Failed to create root partition."
+  for i in {0..99}; do
+    if test -a "${device}"4; then
+      break
+    fi
+    echo -n .
+    sleep .1
+  done
+  echo
   # Are you sure you want to blow away this partition?  YES
   {
-    pass show aaron/"${host}"/luks \
-      || fail "Failed to retrieve password for LUKS."
+    echo -n $(
+      pass show aaron/"${host}"/luks \
+        || fail "Failed to retrieve password for LUKS."
+    )
   } \
-  | sudo cryptsetup luksFormat --key-file - "${device}"3 \
+  | sudo cryptsetup luksFormat --key-file - "${device}"4 \
     || fail "Failed to format for LUKS."
   {
-    pass show aaron/"${host}"/luks \
-      || fail "Failed to retrieve password for LUKS."
+    echo -n $(
+      pass show aaron/"${host}"/luks \
+        || fail "Failed to retrieve password for LUKS."
+    )
   } \
-  | sudo cryptsetup open --key-file - --type luks "${device}"3 "${host}"_crypt \
+  | sudo cryptsetup open --key-file - --type luks "${device}"4 "${host}"_crypt \
     || fail "Failed to open LUKS volume."
   sudo pvcreate /dev/mapper/"${host}"_crypt \
     || fail "Failed to create LVM physical volume over LUKS."
