New workstation.  A few tweaks to partition handling.  Yet more efforts to eliminate the attempt to resize the filesystem on first boot.  (It still happens.)

diff --git a/image_pi_card b/image_pi_card
--- a/image_pi_card
+++ b/image_pi_card
@@ -1,11 +1,13 @@
 #!/bin/bash
 
-card_device=/dev/sdc
+#card_device=/dev/sdc
+card_device=/dev/sdd
 label=log
 mount_point=/var/log
 wired_interface=eth0
 wireless_interface=wlan0
 root_partition_index=1
+big_partition_index=2
 
 
 main() {
@@ -18,7 +20,9 @@ main() {
       ;;
     spy)
       image=~/images/raspberry_pi/raspios.img
+      boot_partition_index=1
       root_partition_index=2
+      big_partition_index=3
       ip_address=192.168.11.67
       label=motion
       mount_point=/var/lib/motion
@@ -26,13 +30,27 @@ main() {
       #wireless_interface=wlan0_disabled
       wired_interface=eth0_disabled
       ;;
+    workstation)
+      image=~/images/raspberry_pi/raspios.img
+      boot_partition_index=1
+      root_partition_index=2
+      big_partition_index=3
+      ip_address=192.168.11.75
+      label=home
+      mount_point=/home
+      kick_wifi=yes
+      #wireless_interface=wlan0_disabled
+      wired_interface=eth0_disabled
+      ;;
     partybus)
       image=~/images/banana_pi/armbian.m2.img
       ip_address=192.168.11.64
-      wireless_interface=wlan0_disabled
+      wired_interface=eth0_disabled
+      #wireless_interface=wlan0_disabled
+      kick_wifi=yes
       ;;
     catcher)
-      debug=yes
+      #debug=yes
       image=~/images/orange_pi/armbian.img
       ip_address=192.168.11.74
       wired_interface=eth0_disabled
@@ -45,12 +63,15 @@ main() {
   esac
 
   root_partition="${card_device}${root_partition_index}"
-  big_partition="${card_device}$(( root_partition_index + 1 ))"
+  if test 'set' = "${boot_partition_index:+set}"; then
+    boot_partition="${card_device}${boot_partition_index}"
+  fi
+  big_partition="${card_device}${big_partition_index}"
 
   get_root
   keep_root &
   sudo_loop_pid=$!
-  for m in /mnt/card /mnt/card2; do
+  for m in /mnt/card/boot /mnt/card /mnt/card2; do
     if mountpoint "${m}" > /dev/null 2>&1; then
       sudo umount "${m}" \
         || fail "Failed to preparatively unmount /mnt/card."
@@ -62,7 +83,16 @@ main() {
     || fail "Failed to mount root partition."
   sudo mount $big_partition /mnt/card2 \
     || fail "Failed to mount big partition."
+  if test 'set' = "${boot_partition:+set}"; then
+    sudo mkdir -p /mnt/card/boot
+    sudo mount $boot_partition /mnt/card/boot \
+      || fail "Failed to mount boot partition."
+  fi
   configure_os
+  if test 'set' = "${boot_partition:+set}"; then
+    sudo umount /mnt/card/boot \
+      || fail "Failed to unmount boot partition."
+  fi
   sudo umount /mnt/card2 \
     || fail "Failed to unmount big partition."
   sudo umount /mnt/card \
@@ -162,6 +192,9 @@ configure_os() {
   done
 
   for file in \
+    /etc/rc3.d/S01resizefs_once \
+    /etc/init.d/resizefs_once \
+    /mnt/card/boot/cmdline.txt \
     /mnt/card/etc/init.d/dhcpcd \
     /mnt/card/etc/profile.d/armbian-check-first-login-reboot.sh \
     /mnt/card/etc/profile.d/armbian-check-first-login.sh \
@@ -310,6 +343,12 @@ EOF
 exit 0
 EOF
 
+  for f in $(ls -a "/mnt/card/${mount_point}/"); do
+    if ! test '.' = "${f}" && ! test '..' = "${f}"; then
+      sudo rm -rf "/mnt/card/${mount_point}/${f}" \
+        || fail "Failed to remove contents of mount point."
+    fi
+  done
   sudo mkdir -p "/mnt/card${mount_point}/" \
     || fail "Failed to create mount point."
   sudo rsync -a "/mnt/card${mount_point}/" /mnt/card2/ \
