Make extensive use of a questionable debugging framework.  Disable predictable interface naming on Armbian.

diff --git a/lib/deploy_image_functions/configure_os b/lib/deploy_image_functions/configure_os
--- a/lib/deploy_image_functions/configure_os
+++ b/lib/deploy_image_functions/configure_os
@@ -4,42 +4,42 @@
 function configure_os() {
   if test 'set' = "${use_big_partition:+set}"; then
     output "Writing big partition line to /etc/fstab."
-    sudo tee -a "${target_mount_point}"/etc/fstab \
-      <<< "LABEL=${big_partition_label} ${big_partition_mount_point} f2fs defaults,noatime,nodiratime 0 2" \
+    eval sudo tee -a '"${target_mount_point}/etc/fstab"' \
+      '<<<' '"LABEL=${big_partition_label} ${big_partition_mount_point} f2fs defaults,noatime,nodiratime 0 2"' ">&${debug_level_file_contents}" \
       || fail "Failed to write big partition line to /etc/fstab"
   fi
 
   if test "set" = "${log_to_disk:+set}"; then
     # log2ram is probably good for sd card life.
     output "Disabling log2ram."
-    sudo sed -i 's/^ENABLED=.*$/ENABLED=false/' "${target_mount_point}"/etc/default/armbian-ramlog \
+    eval sudo sed -i "'"'s/^ENABLED=.*$/ENABLED=false/'"'" '"${target_mount_point}/etc/default/armbian-ramlog"' ">&${debug_level_command_output}" \
       || fail "Failed to disabled log2ram."
   fi
 
   write_root_password_hash
 
   output "Deleting password hash for pi."
-  sudo sed -i 's/^pi:.*$/pi:*:18409:0:99999:7:::/' "${target_mount_point}"/etc/shadow \
+  eval sudo sed -i "'s/^pi:.*\$/pi:*:18409:0:99999:7:::/'" '"${target_mount_point}/etc/shadow"' ">&${debug_level_command_output}" \
     || fail "Failed to delete password hash for pi."
 
   output "Disabling password authentication for pi."
-  sudo sed -Ei 's/^pi:[^:]*:(.*)$/pi:*:\1\/home\/pi:\/bin\/bash/' "${target_mount_point}"/etc/passwd \
+  eval sudo sed -Ei "'s/^pi:[^:]*:(.*)\$/pi:*:\\1\\/home\\/pi:\\/bin\\/bash/'" '"${target_mount_point}/etc/passwd"' ">&${debug_level_command_output}" \
     || fail "Failed to disable password authentication for pi."
 
   for dir in "${create_directories[@]}"; do
     output "Creating directory:  ${target_mount_point}/${dir}"
-    sudo mkdir -p "${target_mount_point}/${dir}"
+    eval sudo mkdir -p '"${target_mount_point}/${dir}"' ">&${debug_level_command_output}"
   done
 
   for file in "${remove_files[@]}"; do 
     output "Removing:  ${file}"
-    sudo rm -f "${target_mount_point}"/$file \
+    eval sudo rm -f '"${target_mount_point}/${file}"' ">&${debug_level_command_output}" \
       || fail "Failed to remove:  ${file}"
   done
 
   for file in "${null_link_files[@]}"; do
     output "Replacing file with symlink to /dev/null:  '${file}'"
-    sudo ln -s /dev/null "${target_mount_point}"/$file \
+    eval sudo ln -s /dev/null '"${target_mount_point}/$file"' ">&${debug_level_command_output}" \
       || fail "Failed to replace file with symlink to /dev/null:  '${file}'"
   done
 
@@ -57,42 +57,54 @@ function configure_os() {
   fi
   template wired_interface_conf /etc/network/interfaces.d/"${wired_interface}"
 
-  otuput "Writing auto line to interfaces file."
-  sudo tee -a "${target_mount_point}"/etc/network/interfaces \
-    <<< "auto ${active_interface}" \
+  output "Writing auto line to interfaces file."
+  eval sudo tee -a '"${target_mount_point}/etc/network/interfaces"' \
+    '<<<' '"auto ${active_interface}"' \
+    ">&${debug_level_file_contents}" \
     || fail "Failed to write auto line to interfaces file."
+
+  if test 'set' = "${disable_predictable_ifnames_for_armbian:+set}"; then
+    output "Disabling predictable network interface naming in:  /boot/armbianEnv.txt"
+    eval sudo tee -a '"${target_mount_point}/boot/armbianEnv.txt"' \
+      '<<<' "'extraargs=net.ifnames=0 biosdevname=0'" \
+      ">&${debug_level_file_contents}" \
+      || fail "Failed to disable preditable network interface naming in:  /boot/armbianEnv.txt"
+  fi
 
   template sshd_config /etc/ssh/sshd_config
 
   output "Writing ssh service file."
-  sudo ln -s /lib/systemd/system/ssh.service "${target_mount_point}"/etc/systemd/system/default.target.wants/ssh.service \
+  eval sudo ln -s /lib/systemd/system/ssh.service '"${target_mount_point}/etc/systemd/system/default.target.wants/ssh.service"' ">&${debug_level_command_output}" \
     || fail "Failed to write ssh service file."
 
   output "Initializing SSH host key (private)."
-  sudo touch "${target_mount_point}"/etc/ssh/ssh_host_rsa_key \
+  eval sudo touch '"${target_mount_point}/etc/ssh/ssh_host_rsa_key"' ">&${debug_level_command_output}" \
     || fail "Failed to initialize SSH host key (private)."
   output "Setting permissions on SSH host key (private)."
-  sudo chmod 0600 "${target_mount_point}"/etc/ssh/ssh_host_rsa_key \
+  eval sudo chmod 0600 '"${target_mount_point}/etc/ssh/ssh_host_rsa_key"' ">&${debug_level_command_output}" \
     || fail "Failed to set permissions on SSH host key (private)."
 
-  host_key_priv_file=../sensitive_ansible/inventory/hosts/${host}/files/ssh_keys/ssh_host_rsa_key
+  host_key_priv_file="../sensitive_ansible/inventory/hosts/${host}/files/ssh_keys/ssh_host_rsa_key"
   output "Writing SSH host key (private)."
   test -e "${host_key_priv_file}" \
     || fail "SSH host key (private) is missing."
-  sudo tee "${target_mount_point}"/etc/ssh/ssh_host_rsa_key \
-    < "${host_key_priv_file}" \
+  eval sudo tee '"${target_mount_point}/etc/ssh/ssh_host_rsa_key"' \
+    '<' '"${host_key_priv_file}"' ">&${debug_level_file_contents}" \
     || fail "Failed to write SSH host key (private)."
 
   host_key_pub_file=../ansible/inventory/hosts/${host}/files/ssh_keys/ssh_host_rsa_key.pub
   output "Writing SSH host key (public)."
   test -e "${host_key_pub_file}" \
     || fail "SSH host key (public) is missing."
-  sudo tee "${target_mount_point}"/etc/ssh/ssh_host_rsa_key.pub \
-    < "${host_key_pub_file}" \
+  eval sudo tee '"${target_mount_point}/etc/ssh/ssh_host_rsa_key.pub"' \
+    '<' '"${host_key_pub_file}"' \
+    ">&${debug_level_file_contents}" \
     || fail "Failed to write SSH host key (public)."
 
   output "Installing authorized key."
-  sudo tee "${target_mount_point}"/root/.ssh/authorized_keys < /home/aaron/.ssh/public \
+  eval sudo tee '"${target_mount_point}/root/.ssh/authorized_keys"' \
+    '<' /home/aaron/.ssh/public \
+    ">&${debug_level_file_contents}" \
     || fail "Failed to install authorized key."
 
   template rc_local_conf /etc/rc.local
@@ -101,18 +113,20 @@ function configure_os() {
     template kick_wifi_conf /usr/local/bin/kick_wifi
 
     output "Setting permissions (0755) on kick_wifi script."
-    sudo chmod 0755 "${target_mount_point}"/usr/local/bin/kick_wifi \
+    eval sudo chmod 0755 '"${target_mount_point}/usr/local/bin/kick_wifi"' ">&${debug_level_command_output}" \
       || fail "Failed to chmod 0755 kick_wifi script."
 
     output "Appending kick_wifi line to:  /etc/rc.local"
-    sudo tee -a "${target_mount_point}"/etc/rc.local \
-      <<< '/usr/local/bin/kick_wifi' \
+    eval sudo tee -a '"${target_mount_point}/etc/rc.local"' \
+      '<<<' '/usr/local/bin/kick_wifi' \
+      ">&${debug_level_file_contents}" \
       || fail "Failed to append kick_wifi line to:  /etc/rc.local"
   fi
 
   output "Writing 'exit 0' line to:  /etc/rc.local"
-  sudo tee -a "${target_mount_point}"/etc/rc.local \
-    <<< 'exit 0' \
+  eval sudo tee -a '"${target_mount_point}/etc/rc.local"' \
+    '<<<' "'exit 0'" \
+      ">&${debug_level_file_contents}" \
     || fail "Failed to write 'exit 0' line to:  /etc/rc.local"
 }
 
diff --git a/lib/deploy_image_functions/partition b/lib/deploy_image_functions/partition
--- a/lib/deploy_image_functions/partition
+++ b/lib/deploy_image_functions/partition
@@ -8,18 +8,18 @@ function create_big_partition() {
       || fail "Failed to analyze device:  '${card_device}'"
   )
   output "Creating big partition."
-  sudo parted -s $card_device mkpart primary 10241MB -- -1MB \
+  eval sudo parted -s '"${card_device}"' mkpart primary 10241MB -- -1MB ">&${debug_level_command_output}" \
     || fail "Failed to write big partition."
   wait_for_device $big_partition
   output "Zeroing beginning of big partition."
-  sudo dd if=/dev/zero of=$big_partition bs=$(( 1024 * 1024 )) count=1 \
+  eval sudo dd if=/dev/zero of='"${big_partition}"' bs=$(( 1024 * 1024 )) count=1 status=none ">&${debug_level_command_output}" \
     || fail "Failed to zero beginning of big partition."
   if ! test 'set' = "${use_big_partition:+set}"; then
     return 0
   fi
 
   output "Writing filesystem to big partition:  ${big_partition}"
-  sudo mkfs.f2fs -f -l "${big_partition_label}" "${big_partition}" \
+  eval sudo mkfs.f2fs -f -l '"${big_partition_label}"' '"${big_partition}"' ">&${debug_level_command_output}" \
     || fail "Failed to write filesystem to big partition."
 }
 
@@ -30,24 +30,24 @@ function sync_big_partition() {
   fi
   output "Mounting:  ${big_partition}"
   output "  ... to:  ${target_mount_point}2"
-  sudo mount -t f2fs "${big_partition}" "${target_mount_point}2" \
+  eval sudo mount -t f2fs '"${big_partition}"' '"${target_mount_point}2"' ">&${debug_level_command_output}" \
     || fail "Failed to mount big partition to alternative mount point."
   output "Syncing old contents of mount point to new big partition..."
   output "... from:  ${target_mount_point}${big_partition_mount_point}/"
   output "  ... to:  ${target_mount_point}2/"
-  sudo mkdir -p "${target_mount_point}${big_partition_mount_point}/" \
+  eval sudo mkdir -p '"${target_mount_point}${big_partition_mount_point}/"' ">&${debug_level_command_output}" \
     || fail "Failed to create mount point."
-  sudo rsync -a "${target_mount_point}${big_partition_mount_point}/" "${target_mount_point}2/" \
+  eval sudo rsync -a '"${target_mount_point}${big_partition_mount_point}/"' '"${target_mount_point}2/"' ">&${debug_level_command_output}" \
     || fail "Failed to sync contents of mount point to big partition."
   output "Removing old contents of mount point."
   for f in $(ls -a "${target_mount_point}${big_partition_mount_point}/"); do
     if ! test '.' = "${f}" && ! test '..' = "${f}"; then
-      sudo rm -rf "${target_mount_point}${big_partition_mount_point}/${f}" \
+      eval sudo rm -rf '"${target_mount_point}${big_partition_mount_point}/${f}"' ">&${debug_level_command_output}" \
         || fail "Failed to remove contents of mount point."
     fi
   done
   output "Unmounting:  ${target_mount_point}2/"
-  sudo umount "${target_mount_point}2/" \
+  eval sudo umount '"${target_mount_point}2/"' ">&${debug_level_command_output}" \
     || fail "Failed to unmount big partition from alternate mount point."
 }
 
@@ -58,6 +58,7 @@ function remove_partitions() {
     index="$(sed 's/^[^0-9]*//g' <<< "${partition_device}")"
     if test '' = "${index}"; then continue; fi
     output "Removing partition ${index}."
-    sudo parted -s "${card_device}" rm "${index}"
+    eval sudo parted -s '"${card_device}"' rm '"${index}"' ">&${debug_level_command_output}" \
+      || fail "Failed to remove partition ${index}."
   done
 }
diff --git a/lib/functions/privilege b/lib/functions/privilege
--- a/lib/functions/privilege
+++ b/lib/functions/privilege
@@ -3,13 +3,13 @@
 
 function get_root() {
   output "We're going to need some root.  Authenticate for sudo."
-  sudo -v || fail "Failed to get root."
+  eval sudo -v ">&${debug_level_command_output}" || fail "Failed to get root."
 }
 
 
 function keep_root() {
   while sleep 60; do 
-    sudo -v || fail "Failed to keep root."
+    eval sudo -v ">&${debug_level_command_output}" || fail "Failed to keep root."
   done
 }
 
@@ -37,5 +37,5 @@ function kill_loop() {
   if test 'unset' = "${loop_pid}"; then
     fail 'kill_loop:  No PID specified.'
   fi
-  kill $loop_pid || fail "Failed to kill loop, PID:  ${loop_pid}"
+  eval kill '"${loop_pid}"' ">&${debug_level_command_output}" || fail "Failed to kill loop, PID:  ${loop_pid}"
 }
